#!/usr/bin/env bash
# Set up autograder files
mkdir -p /autograder/results
rm /autograder/results/results.json
sudo chown -R matlab:matlab /autograder/results
cd /autograder
matlab-batch -licenseToken "$LICENSE_TOKEN" "autograde_prog"

