#!/usr/bin/env bash
# Set up autograder files

cp /autograder/submission/prog.m /autograder/source/prog.m

cd /autograder/source

#sudo adduser runner --no-create-home --disabled-password --gecos ""

#Secured version of the runner
#sudo -u runner octave autograde_prog.m
docker run -ti \
       -v `pwd`/autograder/results:/autograder/results \
       localhost/gradescope-matlab-autograder:latest \
       matlab-batch \
       -licenseToken "$(LICENSE_TOKEN)" \
       "autograder_prog"

